name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js 10.15.0
        uses: actions/setup-node@v1
        with:
          node-version: 10.15.0
      - name: install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test:cov
      - name: build
        run: npm run build
